package cl.cerveceria.View;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victor
 */
public class InformePrincipal extends javax.swing.JFrame {
    InformeMovimientos frnInformeMovimientos = new InformeMovimientos();
    InformeStock frnInformeStock = new InformeStock();
    InformeVentas frnInformeVentas = new InformeVentas();

    /** Creates new form VentaProducto */
    public InformePrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInforme = new javax.swing.JPanel();
        btnCantMovimientos = new javax.swing.JButton();
        btnVentasTipo = new javax.swing.JButton();
        btnTipoCerveza = new javax.swing.JButton();
        btnProductoSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        pnlInforme.setBorder(javax.swing.BorderFactory.createTitledBorder("Informes"));

        btnCantMovimientos.setText("Cantidad de movimientos por tipo ");
        btnCantMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantMovimientosActionPerformed(evt);
            }
        });

        btnVentasTipo.setText("Ventas por tipo de cerveza");
        btnVentasTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasTipoActionPerformed(evt);
            }
        });

        btnTipoCerveza.setText("Cantidad por tipo de cerveza");
        btnTipoCerveza.setToolTipText("");
        btnTipoCerveza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCervezaActionPerformed(evt);
            }
        });

        btnProductoSiguiente.setText("Volver");
        btnProductoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformeLayout = new javax.swing.GroupLayout(pnlInforme);
        pnlInforme.setLayout(pnlInformeLayout);
        pnlInformeLayout.setHorizontalGroup(
            pnlInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformeLayout.createSequentialGroup()
                .addGroup(pnlInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformeLayout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addGroup(pnlInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCantMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnVentasTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTipoCerveza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlInformeLayout.createSequentialGroup()
                        .addGap(625, 625, 625)
                        .addComponent(btnProductoSiguiente)))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        pnlInformeLayout.setVerticalGroup(
            pnlInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnTipoCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVentasTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCantMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductoSiguiente)
                .addContainerGap(716, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(pnlInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipoCervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCervezaActionPerformed
        if (!frnInformeStock.isVisible()){
            frnInformeStock.setVisible(true);
            frnInformeStock.getTablaStockTipoProducto();
        }
            
    }//GEN-LAST:event_btnTipoCervezaActionPerformed

    private void btnCantMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantMovimientosActionPerformed
        if (!frnInformeMovimientos.isVisible()){
            frnInformeMovimientos.setVisible(true);
            frnInformeMovimientos.getTablaMovimientos();
            
        }
    }//GEN-LAST:event_btnCantMovimientosActionPerformed

    private void btnProductoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoSiguienteActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnProductoSiguienteActionPerformed

    private void btnVentasTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasTipoActionPerformed
        if (!frnInformeVentas.isVisible()) {
            frnInformeVentas.setVisible(true);
            frnInformeVentas.getTablaVentas();
        }
    }//GEN-LAST:event_btnVentasTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCantMovimientos;
    private javax.swing.JButton btnProductoSiguiente;
    private javax.swing.JButton btnTipoCerveza;
    private javax.swing.JButton btnVentasTipo;
    private javax.swing.JPanel pnlInforme;
    // End of variables declaration//GEN-END:variables

}
