package cl.cerveceria.View;


import cl.cerveceria.Controller.VentaJpaController;
import cl.cerveceria.Model.Venta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victor
 */
public class InformeVentas extends javax.swing.JFrame {
    
    VentaJpaController ventaController = new VentaJpaController();
    Venta venta = new Venta();

    /** Creates new form VentaProducto */
    public InformeVentas() {
        initComponents();
        getTablaVentas();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProductoNuevaVenta = new javax.swing.JPanel();
        btnProductoSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        pnlProductoNuevaVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas por tipo de cerveza"));

        btnProductoSiguiente.setText("Volver");
        btnProductoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoSiguienteActionPerformed(evt);
            }
        });

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Stock", "Detalle", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblStock);

        javax.swing.GroupLayout pnlProductoNuevaVentaLayout = new javax.swing.GroupLayout(pnlProductoNuevaVenta);
        pnlProductoNuevaVenta.setLayout(pnlProductoNuevaVentaLayout);
        pnlProductoNuevaVentaLayout.setHorizontalGroup(
            pnlProductoNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevaVentaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnProductoSiguiente)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlProductoNuevaVentaLayout.setVerticalGroup(
            pnlProductoNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevaVentaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlProductoNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProductoSiguiente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(679, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlProductoNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlProductoNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoSiguienteActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnProductoSiguienteActionPerformed

    
    public void getTablaVentas(){
        String col[] = {"TIPO CERVEZA","CANTIDAD"};
        int ventaLager = 0;
        int ventaAmbar = 0;
        int ventaStout = 0;
        DefaultTableModel tablaVista = new DefaultTableModel(col, 0);
        Object[] tablaBD = new Object[2];
        List ls;
        try {
            ls = ventaController.findVentaEntities();
            for (int i = 0; i < ls.size(); i++) {
                venta = (Venta)ls.get(i);
                if ("lager".equals(venta.getProductoIdProducto().getTipoProducto().toLowerCase())) {
                    ventaLager = ventaLager + venta.getCantidadVenta();
                } else if ("ambar".equals(venta.getProductoIdProducto().getTipoProducto().toLowerCase())) {
                    ventaAmbar = ventaAmbar + venta.getCantidadVenta();
                } else if ("stout".equals(venta.getProductoIdProducto().getTipoProducto().toLowerCase())) {
                    ventaStout = ventaStout + venta.getCantidadVenta();
                }
            }
            
            tablaBD[0] = "Lager";
            tablaBD[1] = String.valueOf(ventaLager);
            tablaVista.addRow(tablaBD);
            tablaBD[0] = "Ambar";
            tablaBD[1] = String.valueOf(ventaAmbar);
            tablaVista.addRow(tablaBD);
            tablaBD[0] = "Stout";
            tablaBD[1] = String.valueOf(ventaStout);
            tablaVista.addRow(tablaBD);
            
            this.tblStock.setModel(tablaVista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al cargar datos");
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductoSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlProductoNuevaVenta;
    private javax.swing.JTable tblStock;
    // End of variables declaration//GEN-END:variables

}
