package cl.cerveceria.View;


import cl.cerveceria.Controller.ClienteJpaController;
import cl.cerveceria.Controller.InventarioJpaController;
import cl.cerveceria.Controller.MovimientoJpaController;
import cl.cerveceria.Controller.ProductoJpaController;
import cl.cerveceria.Controller.VentaJpaController;
import cl.cerveceria.Model.Cliente;
import cl.cerveceria.Model.Inventario;
import cl.cerveceria.Model.Movimiento;
import cl.cerveceria.Model.Producto;
import cl.cerveceria.Model.Venta;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VentaProducto extends javax.swing.JFrame {
    
    ClienteJpaController clienteController = new ClienteJpaController();
    Cliente cliente = new Cliente();
    InventarioJpaController inventarioController = new InventarioJpaController();
    Inventario inventario = new Inventario();
    VentaJpaController ventaController = new VentaJpaController();
    Venta venta = new Venta();
    ProductoJpaController productoController = new ProductoJpaController();
    Producto producto = new Producto();
    MovimientoJpaController movimientoController = new MovimientoJpaController();
    Movimiento movimiento = new Movimiento();
    
    int precio = 0;
    
    /** Creates new form VentaProducto */
    public VentaProducto() {
        initComponents();
        setearFechaVenta();
        getTablaTotalProductos();
    }
    
    private void setearFechaVenta(){
        String fechaFormateada;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaActual = new Date();
        fechaFormateada = sdf.format(fechaActual);
        lblFechaActual.setText(fechaFormateada);
    }
    
    public void getTablaTotalProductos(){
        String col[] = {"ID PRODUCTO","MARCA CERVEZA","TIPO CERVEZA","FORMATO","GRADO ETILICO","PRECIO","STOCK"};
        DefaultTableModel tablaVista = new DefaultTableModel(col, 0);
        Object[] tablaBD = new Object[7];
        List ls;
        try {
            ls = inventarioController.findInventarioEntities();
            for(int i = 0; i < ls.size(); i++){
                inventario = (Inventario)ls.get(i);
                tablaBD[0] = inventario.getProductoIdProducto().getIdProducto();
                tablaBD[1] = inventario.getProductoIdProducto().getNombreProducto();
                tablaBD[2] = inventario.getProductoIdProducto().getTipoProducto();
                tablaBD[3] = inventario.getProductoIdProducto().getFormato();
                tablaBD[4] = inventario.getProductoIdProducto().getGradoEtilico();
                tablaBD[5] = inventario.getProductoIdProducto().getPrecioVenta();
                tablaBD[6] = inventario.getStock();
                tablaVista.addRow(tablaBD);
            }
            this.tblStock.setModel(tablaVista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al cargar datos");
        }
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProductoNuevaVenta = new javax.swing.JPanel();
        pnlProducto = new javax.swing.JPanel();
        lblMarcaCerveza = new javax.swing.JLabel();
        lblTipoCerveza = new javax.swing.JLabel();
        lblFormato = new javax.swing.JLabel();
        lblGrados = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblFechaVenta = new javax.swing.JLabel();
        lblFechaVenta1 = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        lblMarcaSet = new javax.swing.JLabel();
        lblTipoCervSet = new javax.swing.JLabel();
        lblFormatoSet = new javax.swing.JLabel();
        lblGrAlcSet = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblPrecioSet = new javax.swing.JLabel();
        lblidProd = new javax.swing.JLabel();
        lblFechaVenta2 = new javax.swing.JLabel();
        lblStockActual = new javax.swing.JLabel();
        lblStockSet = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        txtRutCliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        lblPrimerAp = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblSegundoAp = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNombreClienteSet = new javax.swing.JLabel();
        lblCorreoSet = new javax.swing.JLabel();
        lblPrimerApSet = new javax.swing.JLabel();
        lblSegundoApSet = new javax.swing.JLabel();
        lblTelefonoSet = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblRutSet = new javax.swing.JLabel();
        lblTipoCliente = new javax.swing.JLabel();
        lblTipoClienteSet = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblNombreEmpresaSet = new javax.swing.JLabel();
        btnProductoVolver = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        pnlProductoNuevaVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva venta"));

        pnlProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        lblMarcaCerveza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMarcaCerveza.setText("Marca cerveza:");

        lblTipoCerveza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoCerveza.setText("Tipo Cerveza:");

        lblFormato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFormato.setText("Formato:");

        lblGrados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrados.setText("Grados alcoholicos:");

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidad.setText("Cantidad:");

        lblFechaVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaVenta.setText("Fecha venta:");

        lblFechaActual.setText("N/A");

        lblMarcaSet.setText("N/A");

        lblTipoCervSet.setText("N/A");

        lblFormatoSet.setText("N/A");

        lblGrAlcSet.setText("N/A");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecio.setText("Precio:");

        lblPrecioSet.setText("N/A");

        lblidProd.setText("N/A");

        lblFechaVenta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaVenta2.setText("Id. Producto:");

        lblStockActual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStockActual.setText("Stock actual:");

        lblStockSet.setText("N/A");

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(lblCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductoLayout.createSequentialGroup()
                                .addComponent(lblTipoCerveza)
                                .addGap(18, 18, 18)
                                .addComponent(lblTipoCervSet))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductoLayout.createSequentialGroup()
                                .addComponent(lblFechaVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFechaActual))
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(lblFechaVenta2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblidProd)))
                        .addGap(142, 142, 142)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrados)
                            .addComponent(lblFormato)
                            .addComponent(lblStockActual))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFormatoSet)
                                    .addComponent(lblGrAlcSet))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFechaVenta1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(lblStockSet)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarcaCerveza)
                            .addComponent(lblPrecio))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioSet)
                            .addComponent(lblMarcaSet))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFechaVenta1)
                .addGap(44, 44, 44))
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaCerveza)
                    .addComponent(lblTipoCerveza)
                    .addComponent(lblFormato)
                    .addComponent(lblMarcaSet)
                    .addComponent(lblTipoCervSet)
                    .addComponent(lblFormatoSet))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaVenta)
                    .addComponent(lblFechaActual)
                    .addComponent(lblGrados)
                    .addComponent(lblGrAlcSet)
                    .addComponent(lblPrecio)
                    .addComponent(lblPrecioSet))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStockSet)
                        .addComponent(lblStockActual))
                    .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCantidad)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblidProd)
                        .addComponent(lblFechaVenta2)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setText("Rut Cliente (12345678-9)");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));
        jPanel1.setToolTipText("");

        lblNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreCliente.setText("Nombre Cliente:");

        lblPrimerAp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrimerAp.setText("Primer Apellido:");

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorreo.setText("Correo Electrónico:");

        lblSegundoAp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSegundoAp.setText("Segundo Apellido:");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefono.setText("Teléfono:");

        lblNombreClienteSet.setText("N/A");

        lblCorreoSet.setText("N/A");

        lblPrimerApSet.setText("N/A");

        lblSegundoApSet.setText("N/A");

        lblTelefonoSet.setText("N/A");

        lblRut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRut.setText("RUT:");

        lblRutSet.setText("N/A");

        lblTipoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoCliente.setText("Tipo Empresa:");

        lblTipoClienteSet.setText("N/A");

        lblEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpresa.setText("Nombre Empresa:");

        lblNombreEmpresaSet.setText("N/A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSegundoAp)
                    .addComponent(lblPrimerAp)
                    .addComponent(lblNombreCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreClienteSet)
                    .addComponent(lblPrimerApSet)
                    .addComponent(lblSegundoApSet))
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo)
                    .addComponent(lblTelefono)
                    .addComponent(lblRut))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRutSet)
                    .addComponent(lblCorreoSet)
                    .addComponent(lblTelefonoSet))
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoCliente)
                    .addComponent(lblEmpresa))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEmpresaSet)
                    .addComponent(lblTipoClienteSet))
                .addGap(409, 409, 409))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblNombreClienteSet))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerAp)
                    .addComponent(lblPrimerApSet))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoAp)
                    .addComponent(lblSegundoApSet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(lblCorreoSet))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(lblTelefonoSet)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoCliente)
                            .addComponent(lblTipoClienteSet))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpresa)
                            .addComponent(lblNombreEmpresaSet))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(lblRutSet))
                .addContainerGap())
        );

        btnProductoVolver.setText("Volver");
        btnProductoVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoVolverActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoNuevaVentaLayout = new javax.swing.GroupLayout(pnlProductoNuevaVenta);
        pnlProductoNuevaVenta.setLayout(pnlProductoNuevaVentaLayout);
        pnlProductoNuevaVentaLayout.setHorizontalGroup(
            pnlProductoNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevaVentaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlProductoNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlProductoNuevaVentaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductoVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizar)
                .addGap(108, 108, 108))
        );
        pnlProductoNuevaVentaLayout.setVerticalGroup(
            pnlProductoNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(btnFinalizar)
                    .addComponent(btnProductoVolver))
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PRODUCTO", "TIPO PRODUCTO", "FORMATO", "GRADO ETILICO", "PRECIO", "Title 6", "Title 7"
            }
        ));
        tblStock.setMaximumSize(new java.awt.Dimension(375, 80));
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlProductoNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlProductoNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnProductoVolverActionPerformed

    private void btnFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarMouseClicked
        if ("N/A".equals(this.lblRutSet.getText())) {
            JOptionPane.showMessageDialog(this, "Debe indicar un cliente");
        } else {
            if ("N/A".equals(this.lblidProd.getText())) {
            JOptionPane.showMessageDialog(this, "Debe elegir un producto");
            } else {
                if (calcularNuevoStock() < 0 || this.txtCantidad.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "La cantidad no puede ser 0 o mayor al Stock actual");
                } else {
                    try {
                        setearDatosVenta();
                        ventaController.create(venta);
                        setearDatosMovimientoEgreso();
                        movimientoController.create(movimiento);
                        setearDatosInventario2();
                        inventarioController.edit(inventario);
                        JOptionPane.showMessageDialog(this, "Venta realizada correctamente");
                        this.setVisible(false);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error al realizar la venta");
                    }
                }                
            }
        }
    }//GEN-LAST:event_btnFinalizarMouseClicked

    private void setearDatosVenta(){
        //venta.setIdVenta(calcularIdVenta());
        venta.setCantidadVenta(Integer.parseInt(this.txtCantidad.getText()));
        venta.setFechaVenta(new Date());
        venta.setTotalPrecioVenta(calcularPrecioTotal());
        venta.setClienteNumrutCliente(calcularCliente());
        venta.setProductoIdProducto(calcularProductoCompra());
    }
    
    private Cliente calcularCliente(){
        List ls;
        try {
            ls = clienteController.findClienteEntities();
            for (int i = 0; i < ls.size(); i++) {
                cliente = (Cliente)ls.get(i);
                if (cliente.getNumrutCliente() == Integer.parseInt(this.lblRutSet.getText().substring(0,this.lblRutSet.getText().length() - 2))) {
                    return cliente;
                }
            }
         
        } catch (Exception e) {
        }
        return cliente;
    }
    
    private int calcularIdVenta(){
        int numId = 0;
        List ls;
        try {
            ls = ventaController.findVentaEntities();
            if (!ls.isEmpty()) {
                numId = Integer.parseInt((String) ls.get(ls.size() -1 )) + 1;
            } else {
                    numId = 1;
            }            
        } catch (Exception e) {
        }
        return numId;
    }
    
    private int calcularPrecioTotal(){
        int precioTotal;
        int cantidad;
        int precio;
        cantidad = Integer.parseInt(this.txtCantidad.getText());
        precio = Integer.parseInt(this.lblPrecioSet.getText());
        precioTotal =  cantidad * precio;
        return precioTotal;    
    }
    
    private Producto calcularProductoCompra(){
        List ls;
        ls = productoController.findProductoEntities();
        for (int i = 0; i < ls.size(); i++) {
            producto = (Producto)ls.get(i);
            if (producto.getIdProducto() == Integer.valueOf(lblidProd.getText())) {
                return producto;
            }
        }
        return producto;
    }
    
    private void setearDatosMovimientoEgreso(){
        movimiento.setCantidadMovimiento(Integer.parseInt(this.txtCantidad.getText()));
        movimiento.setFechaMovimiento(new Date());
        movimiento.setProductoIdProducto(calcularProductoCompra());
        movimiento.setTipoMovimiento("Egreso");
        //movimiento.setIdMovimiento(calcularIdMovimiento());
    }
    
    private int calcularIdMovimiento(){
        int numId = 0;
        List ls;
        try {
            ls = movimientoController.findMovimientoEntities();
            if (!ls.isEmpty()) {
                numId = Integer.parseInt((String) ls.get(ls.size() -1 )) + 1;
            } else {
                    numId = 1;
            }            
        } catch (Exception e) {
        }
        return numId;
    }
    
    
    private void setearDatosInventario2(){
        inventario.setIdinventario(calcularIdInventario());
        inventario.setProductoIdProducto(calcularProductoCompra());
        inventario.setStock(calcularNuevoStock());
    }
    
    private int calcularIdInventario(){
        int numId = 0;
        List ls;
        try {
            ls = inventarioController.findInventarioEntities();
            for (int i = 0; i < ls.size(); i++) {
                inventario = (Inventario)ls.get(i);
                if (inventario.getIdinventario() == Integer.valueOf(this.lblidProd.getText())) {
                    numId = inventario.getIdinventario();
                    return numId;
                }
            }
        } catch (Exception e) {
        }
        return numId;
    }
    
    private int calcularNuevoStock(){
        int stock = 0;
        
        return stock = Integer.parseInt(this.lblStockSet.getText()) - Integer.parseInt(this.txtCantidad.getText());
    }
    
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String numRunBD = "";
        String dvRunBD = "";
        List ls;
        try {
            ls = clienteController.findClienteEntities();
            for (int i = 0; i < ls.size(); i++) {
                cliente = (Cliente)ls.get(i);
                numRunBD = cliente.getNumrutCliente().toString();
                dvRunBD = cliente.getDvrutCliente();
                if (txtRutCliente.getText().equals(numRunBD + "-" + dvRunBD)) {
                    cargarDatosCliente();
                    JOptionPane.showMessageDialog(this, "Datos cargados correctamente");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cliente no existe");
        }
        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void cargarDatosCliente(){
        lblNombreClienteSet.setText(cliente.getNombreCliente());
        lblPrimerApSet.setText(cliente.getAppaternoCliente());
        lblSegundoApSet.setText(cliente.getApmaternoCliente());
        lblCorreoSet.setText(cliente.getEmailCliente());
        lblTelefonoSet.setText(String.valueOf(cliente.getTelefonoCliente()));
        lblRutSet.setText(cliente.getNumrutCliente() + "-" + cliente.getDvrutCliente());
        lblTipoClienteSet.setText(cliente.getTipoEmpresa());
        lblNombreClienteSet.setText(cliente.getNombreCliente());
    }
    
    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        lblMarcaSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),1).toString());
        lblTipoCervSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),2).toString());
        lblFormatoSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),3).toString());
        lblGrAlcSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),4).toString());
        lblPrecioSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),5).toString());
        lblidProd.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),0).toString());
        lblStockSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tblStockMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnProductoVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoSet;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblFechaVenta1;
    private javax.swing.JLabel lblFechaVenta2;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblFormatoSet;
    private javax.swing.JLabel lblGrAlcSet;
    private javax.swing.JLabel lblGrados;
    private javax.swing.JLabel lblMarcaCerveza;
    private javax.swing.JLabel lblMarcaSet;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreClienteSet;
    private javax.swing.JLabel lblNombreEmpresaSet;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioSet;
    private javax.swing.JLabel lblPrimerAp;
    private javax.swing.JLabel lblPrimerApSet;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblRutSet;
    private javax.swing.JLabel lblSegundoAp;
    private javax.swing.JLabel lblSegundoApSet;
    private javax.swing.JLabel lblStockActual;
    private javax.swing.JLabel lblStockSet;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoSet;
    private javax.swing.JLabel lblTipoCervSet;
    private javax.swing.JLabel lblTipoCerveza;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JLabel lblTipoClienteSet;
    private javax.swing.JLabel lblidProd;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JPanel pnlProductoNuevaVenta;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtRutCliente;
    // End of variables declaration//GEN-END:variables

}
