package cl.cerveceria.View;


import cl.cerveceria.Controller.InventarioJpaController;
import cl.cerveceria.Controller.MovimientoJpaController;
import cl.cerveceria.Controller.ProductoJpaController;
import cl.cerveceria.Model.Inventario;
import cl.cerveceria.Model.Movimiento;
import cl.cerveceria.Model.Producto;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VistaInventario extends javax.swing.JFrame {
    
    InventarioJpaController inventarioController = new InventarioJpaController();
    Inventario inventario = new Inventario();
    
    ProductoJpaController productoController = new ProductoJpaController();
    Producto producto = new Producto();
    
    MovimientoJpaController movimientoController = new MovimientoJpaController();
    Movimiento movimiento = new Movimiento();
    
    /** Creates new form VentaProducto */
    public VistaInventario() {
        initComponents();
        getTablaTotalInventario();
    }
    
   
    public void getTablaTotalInventario(){
        String col[] = {"ID","MARCA CERVEZA","TIPO CERVEZA","FORMATO","GRADO ETILICO","PRECIO COSTO","PRECIO VENTA","STOCK"};
        DefaultTableModel tablaVista = new DefaultTableModel(col, 0);
        Object[] tablaBD = new Object[8];
        List ls;
        try {
            ls = inventarioController.findInventarioEntities();
            for(int i = 0; i < ls.size(); i++){
                inventario = (Inventario)ls.get(i);
                tablaBD[0] = inventario.getIdinventario();
                tablaBD[1] = inventario.getProductoIdProducto().getNombreProducto();
                tablaBD[2] = inventario.getProductoIdProducto().getTipoProducto();
                tablaBD[3] = inventario.getProductoIdProducto().getFormato();
                tablaBD[4] = inventario.getProductoIdProducto().getGradoEtilico();
                tablaBD[5] = inventario.getProductoIdProducto().getCosto();
                tablaBD[6] = inventario.getProductoIdProducto().getPrecioVenta();
                tablaBD[7] = inventario.getStock();
                tablaVista.addRow(tablaBD);
            }
            this.tblStock.setModel(tablaVista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al cargar datos");
        }
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInventario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        pnlProducto = new javax.swing.JPanel();
        lblFechaVenta1 = new javax.swing.JLabel();
        lblIdProd = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        lblIdProdSet = new javax.swing.JLabel();
        lblStockActualSet = new javax.swing.JLabel();
        lblAgregarStock = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        txtAgregarStock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        pnlInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PRODUCTO", "TIPO PRODUCTO", "FORMATO", "GRADO ETILICO", "PRECIO"
            }
        ));
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        pnlProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        lblIdProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdProd.setText("Id. Producto:");

        lblStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStock.setText("Stock:");

        btnModificar.setText("Agregar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lblIdProdSet.setText("N/A");

        lblStockActualSet.setText("N/A");

        lblAgregarStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAgregarStock.setText("Agregar Stock:");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(lblAgregarStock)
                        .addGap(18, 18, 18)
                        .addComponent(txtAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(437, 437, 437)
                        .addComponent(lblFechaVenta1))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdProd)
                            .addComponent(lblStock))
                        .addGap(30, 30, 30)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStockActualSet)
                            .addComponent(lblIdProdSet))
                        .addGap(94, 94, 94)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProd)
                    .addComponent(btnModificar)
                    .addComponent(lblIdProdSet)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStockActualSet))
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(lblFechaVenta1)
                        .addGap(44, 44, 44))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgregarStock)
                            .addComponent(txtAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addGroup(pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventarioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventarioLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventarioLayout.createSequentialGroup()
                .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pnlInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(pnlInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        lblIdProdSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),0).toString());
        lblStockActualSet.setText(this.tblStock.getValueAt(this.tblStock.getSelectedRow(),7).toString());
    }//GEN-LAST:event_tblStockMouseClicked

    
    
    private int calcularIdInventario(){
        int numId = 0;
        List ls;
        try {
            ls = inventarioController.findInventarioEntities();
            for (int i = 0; i < ls.size(); i++) {
                inventario = (Inventario)ls.get(i);
                if (inventario.getIdinventario() == Integer.valueOf(this.lblIdProdSet.getText())) {
                    numId = inventario.getIdinventario();
                    return numId;
                }
            }
        } catch (Exception e) {
        }
        return numId;
    }
    
    private Producto calcularProductoCompra(){
        List ls;
        ls = productoController.findProductoEntities();
        for (int i = 0; i < ls.size(); i++) {
            producto = (Producto)ls.get(i);
            if (producto.getIdProducto() == Integer.valueOf(this.lblIdProd.getText())) {
                return producto;
            }
        }
        return producto;
    }
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            setearDatosInventario();
            inventarioController.edit(inventario);
            setearDatosMovimiento();
            movimientoController.create(movimiento);
            JOptionPane.showMessageDialog(this, "Producto modificado correctamente");
            getTablaTotalInventario();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar el producto");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarStockActionPerformed

    private void setearDatosInventario(){
        inventario.setIdinventario(calcularIdInventario());
        inventario.setProductoIdProducto(calcularProducto());
        inventario.setStock(Integer.parseInt(this.lblStockActualSet.getText()) +  Integer.parseInt(this.txtAgregarStock.getText()));
    }
    
    
    private Producto calcularProducto(){
        List ls;
        ls = productoController.findProductoEntities();
        for (int i = 0; i < ls.size(); i++) {
            producto = (Producto)ls.get(i);
            if (producto.getIdProducto() == Integer.valueOf(this.lblIdProdSet.getText())) {
                return producto;
            }
        }
        return producto;
    }
    
    private void setearDatosMovimiento(){
        movimiento.setCantidadMovimiento(Integer.parseInt(this.txtAgregarStock.getText()));
        movimiento.setFechaMovimiento(new Date());
        movimiento.setProductoIdProducto(calcularProducto());
        movimiento.setTipoMovimiento("Ingreso");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregarStock;
    private javax.swing.JLabel lblFechaVenta1;
    private javax.swing.JLabel lblIdProd;
    private javax.swing.JLabel lblIdProdSet;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblStockActualSet;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtAgregarStock;
    // End of variables declaration//GEN-END:variables

}
